config/routes.rb
Rails.application.routes.draw do
  resources :orders

  devise_for :admins, :controllers => {:sessions => "admins/sessions", :registrations => "admins/registrations"}

  resources :admins

  resources :paint_types

  resources :sizes

  resources :exhibitions

  resources :homes

  

  resources :photos

  resources :paints

  resources :artists

  root 'homes#home'
  get 'contact' => 'homes#contact'
  match 'contact',     to: 'homes#contact', via: 'get'
  get 'art_gallery' => 'homes#art_gallery'
  get 'artist_detail' => 'homes#artist'
  get 'photo_gallery' => 'homes#photo_gallery'
  get 'exhibition' => 'homes#exhibition'
  get 'terms_and_conditions' => 'homes#terms_and_conditions'
  get 'search' => 'homes#art_gallery'
  get 'search_photo' => 'homes#photo_gallery'
  get "artist_profile/:id" => "homes#artist_profile"
  get "artist_artwork" => "homes#artist_artwork"
  

 

 

 

end

app/models/artist.rb
class Artist < ActiveRecord::Base

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


	has_many :paints

	has_many :photos
	
	PAINTER_TYPE = [
	"Painter",
	"Photographer"]

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  layout "backend"
  before_action :authenticate_admin!
  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:avatar, :name, :date_of_birth, :desc, :painter_type)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist, :html => { :class =>"form-horizontal" } do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this exhibition from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
            </div>
  </div>
  <% end %>


 <div class="control-group">
    <label class="control-label" for="inputEmail">Name</label>
        <div class="controls">
            <%= f.text_field :name %>
        </div>
  </div>
 <div class="control-group">
    <label class="control-label" for="inputEmail">DOB</label>
        <div class="controls">
            <%= f.text_field :date_of_birth %>
        </div>
  </div>
 <div class="control-group">
    <label class="control-label" for="inputEmail">Description</label>
        <div class="controls">
          <%= f.text_area :desc, :cols =>'6', :rows =>'4' %>
        </div>
  </div>
 <div class="control-group">
    <label class="control-label" for="inputEmail">Professional</label>
        <div class="controls">
            <%= f.select(:painter_type, Artist::PAINTER_TYPE) %>
        </div>
  </div>

   <div class="control-group">
    <label class="control-label" for="inputEmail">Avatar</label>
        <div class="controls">
          <%= f.file_field :avatar %>
        </div>
  </div>
  
   <div class="control-group">
        <div class="controls">
                <%= f.submit :class => "btn" %>
        </div>
  </div>

<% end %>

app/views/artists/edit.html.erb
<ul class="breadcrumb">
	<li><a href="#" id="a_style">Admin Panel</a> <span class="divider">/</span></li>
    <li><a href="#" id="a_style">Dashboard</a> <span class="divider">/</span></li>
    <li class="active">Artists</li>
</ul>

<div class="page-header">
  <h1>Edit Profile <small>details infomation</small></h1>
</div>
<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<ul class="breadcrumb">
  <li><a href="#" id="a_style">Admin Panel</a> <span class="divider">/</span></li>
    <li><a href="#" id="a_style">Dashboard</a> <span class="divider">/</span></li>
    <li class="active">Artists</li>
</ul>

<div class="page-header">
  <h1>Artists data<small> list of artist infomation</small></h1>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Date of birth</th>
      <th>Description</th>
      <th>Professional</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.name %></td>
        <td><%= artist.date_of_birth %></td>
        <td><%= artist.desc %></td>
        <td><%= artist.painter_type %></td>
        <td><%= link_to 'Show', artist, :id => "a_style" %></td>
        <td><%= link_to 'Edit', edit_artist_path(artist), :id => "a_style" %></td>
        <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' }, :id => "a_style" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artist', new_artist_path, :class =>"btn btn-default" %>

app/views/artists/new.html.erb
<ul class="breadcrumb">
	<li><a href="#" id="a_style">Admin Panel</a> <span class="divider">/</span></li>
    <li><a href="#" id="a_style">Dashboard</a> <span class="divider">/</span></li>
    <li class="active">Artists</li>
</ul>
<div class="page-header">
  <h1>New Artist <small>data entry form</small></h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<ul class="breadcrumb">
	<li><a href="#" id="a_style">Admin Panel</a> <span class="divider">/</span></li>
    <li><a href="#" id="a_style">Dashboard</a> <span class="divider">/</span></li>
    <li class="active">Artists</li>
</ul>
<h1 id="notice"><%= notice %></h1>

<div class="page-header">
  <h1>Artist Profile <small>details infomation</small></h1>
</div>

<p class="lead" id="showtxt">
  <strong>Name:</strong>
  <%= @artist.name %>
</p>

<p class="lead" id="showtxt">
  <strong>Date of birth:</strong>
  <%= @artist.date_of_birth %>
</p>
<p class="lead" id="showtxt">
  <strong><u>Description</u></strong><br/>
  <%= @artist.desc %>
</p>

<p class="lead" id="showtxt">
  <strong>Professional:</strong>
  <%= @artist.painter_type %>
</p>

<p class="lead" id="showtxt">
  <%= image_tag @artist.avatar.url(:medium) %>
</p>

<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>