config/routes.rb
Rails.application.routes.draw do
  resources :orders

  devise_for :admins, :controllers => {:sessions => "admins/sessions", :registrations => "admins/registrations"}

  resources :admins

  resources :paint_types

  resources :sizes

  resources :exhibitions

  resources :homes

  

  resources :photos

  resources :paints

  resources :artists

  root 'homes#home'
  get 'contact' => 'homes#contact'
  match 'contact',     to: 'homes#contact', via: 'get'
  get 'art_gallery' => 'homes#art_gallery'
  get 'artist_detail' => 'homes#artist'
  get 'photo_gallery' => 'homes#photo_gallery'
  get 'exhibition' => 'homes#exhibition'
  get 'terms_and_conditions' => 'homes#terms_and_conditions'
  get 'search' => 'homes#art_gallery'
  get 'search_photo' => 'homes#photo_gallery'
  get "artist_profile/:id" => "homes#artist_profile"
  get "artist_artwork" => "homes#artist_artwork"
  

 

 

 

end

app/models/paint.rb
class Paint < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  belongs_to :artist
  belongs_to :size
  belongs_to :paint_type

  before_save :generate_item_code


  	OUR_ARTWORK = ["YES","NO"]
  	NEW_ARRIVAL = ["YES","NO"]

	def self.search(paint_type_id,size_id,artist_id)
	  where('paint_type_id = ? AND size_id = ? AND artist_id = ?', "#{paint_type_id}", "#{size_id}", "#{artist_id}")
	end


	def generate_item_code
	

		number = Paint.maximum(:id).to_i + 1
	
		if
	   	 number.to_s.length == 1
			zero = "000"
	   		self.item_code = "CC-" + zero + number.to_s
	   	elsif
	   	 number.to_s.length == 2
			zero = "00"
	   		self.item_code = "CC-" + zero + number.to_s
	   	elsif
	   	 number.to_s.length == 3
			zero = "0"
	   		self.item_code = "CC-" + zero + number.to_s
	   	elsif
	   		number.to_s.length == 4
			number = Paint.last.id + 1
	   		self.item_code = "CC-" + number.to_s
	   	end
	end


  
end

app/models/paint_type.rb
class PaintType < ActiveRecord::Base
	has_many :paints
end

app/controllers/paints_controller.rb
class PaintsController < ApplicationController
  before_action :set_paint, only: [:show, :edit, :update, :destroy]
  layout "backend"
  before_action :authenticate_admin!
  # GET /paints
  # GET /paints.json
  def index
    @paints = Paint.all
  end


  # GET /paints/1
  # GET /paints/1.json
  def show
  end

  # GET /paints/new
  def new
    @paint = Paint.new
  end

  # GET /paints/1/edit
  def edit
  end

  # POST /paints
  # POST /paints.json
  def create
    @paint = Paint.new(paint_params)

    respond_to do |format|
      if @paint.save
        format.html { redirect_to @paint, notice: 'Paint was successfully created.' }
        format.json { render :show, status: :created, location: @paint }
      else
        format.html { render :new }
        format.json { render json: @paint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paints/1
  # PATCH/PUT /paints/1.json
  def update
    respond_to do |format|
      if @paint.update(paint_params)
        format.html { redirect_to @paint, notice: 'Paint was successfully updated.' }
        format.json { render :show, status: :ok, location: @paint }
      else
        format.html { render :edit }
        format.json { render json: @paint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paints/1
  # DELETE /paints/1.json
  def destroy
    @paint.destroy
    respond_to do |format|
      format.html { redirect_to paints_url, notice: 'Paint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paint
      @paint = Paint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paint_params
      params.require(:paint).permit(:item_code, :our_artwork, :new_arrival,:published_date, :title, :avatar, :paint_type_id, :color, :size, :price, :artist_id, :size_id)
    end
end

app/helpers/paints_helper.rb
module PaintsHelper
end

app/views/paints/_form.html.erb
<%= form_for @paint, :html => { :multipart => true, :class =>"form-horizontal" } do |f| %>
  <% if @paint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paint.errors.count, "error") %> prohibited this paint from being saved:</h2>

      <ul>
      <% @paint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  </div>
  <% end %>

   <div class="control-group">
    <label class="control-label" for="inputEmail">Title</label>
        <div class="controls">
          <%= f.text_field :title %>
        </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="inputEmail">Type</label>
        <div class="controls">
          <%= f.select :paint_type_id, PaintType.all.collect { |c| [c.type_name, c.id] } %>
        </div>
  </div>



  <div class="control-group">
    <label class="control-label" for="inputEmail">Size</label>
        <div class="controls">
          <%= f.select :size_id, Size.all.collect { |c| [c.size, c.id] }%>
        </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="inputEmail">Price</label>
        <div class="controls">
          <%= f.text_field :price %>
        </div>
  </div>


  <div class="control-group">
    <label class="control-label" for="inputEmail">Is that new arrival</label>
        <div class="controls">
          <%= f.select(:new_arrival, Paint::NEW_ARRIVAL, {include_blank: 'Choose'}) %>
        </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="inputEmail">Is that our art work</label>
        <div class="controls">
          <%= f.select(:our_artwork, Paint::OUR_ARTWORK, {include_blank: 'Choose'}) %>
        </div>
  </div>


   <div class="control-group">
    <label class="control-label" for="inputEmail">Artist</label>
        <div class="controls">
          <%= f.select :artist_id, Artist.where("painter_type='Painter'").collect { |c| [c.name, c.id] } %>
        </div>
  </div>

   <div class="control-group">
    <label class="control-label" for="inputEmail">Avatar</label>
        <div class="controls">
          <%= f.file_field :avatar %>
        </div>
  </div>

   <div class="control-group">
        <div class="controls">
      <%= f.submit  :class => "btn" %>
  </div>
  </div>
<% end %>

app/views/paints/edit.html.erb
<ul class="breadcrumb">
  <li><a href="#" id="a_style">Admin Panel</a> <span class="divider">/</span></li>
    <li><a href="#" id="a_style">Dashboard</a> <span class="divider">/</span></li>
    <li class="active">Paints</li>
</ul>
<div class="page-header">
  <h1>Edit Paint <small>details infomation</small></h1>
</div>

<%= render 'form' %>

<%= link_to 'Show', @paint %> |
<%= link_to 'Back', paints_path %>

app/views/paints/index.html.erb
<ul class="breadcrumb">
  <li><a href="#" id="a_style">Admin Panel</a> <span class="divider">/</span></li>
    <li><a href="#" id="a_style">Dashboard</a> <span class="divider">/</span></li>
    <li class="active">Paints</li>
</ul>
<div class="page-header">
  <h1>Paints data<small> list of paint infomation</small></h1>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Code</th>
      <th>Title</th>
      <th>Paint Type</th>
      <th>Size</th>
      <th>Price</th>
      <th>Artist Name</th>
      <th>Our Artwork</th>
      <th>New Arrival</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paints.each do |paint| %>
      <tr>
        <td><%= paint.item_code rescue "-" %></td>
        <td><%= paint.title rescue "-" %></td>
        <td><%= paint.paint_type.type_name rescue "-" %></td>
        <td><%= paint.size.size rescue "-" %></td>
        <td><%= paint.price rescue "-" %></td>
        <td><%= paint.artist.name rescue "-" %></td>
        <td><%= paint.our_artwork rescue "-" %></td>
        <td><%= paint.new_arrival rescue "-" %></td>
        <td><%= link_to 'Show', paint, :id => "a_style" %></td>
        <td><%= link_to 'Edit', edit_paint_path(paint), :id => "a_style" %></td>
        <td><%= link_to 'Destroy', paint, method: :delete, data: { confirm: 'Are you sure?' }, :id => "a_style" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paint', new_paint_path, :class => "btn btn-default" %>

<br>
<br>

app/views/paints/new.html.erb
<ul class="breadcrumb">
  <li><a href="#" id="a_style">Admin Panel</a> <span class="divider">/</span></li>
    <li><a href="#" id="a_style">Dashboard</a> <span class="divider">/</span></li>
    <li class="active">Paints</li>
</ul>
<div class="page-header">
  <h1>New Paint <small>data entry form</small></h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', paints_path %>

app/views/paints/show.html.erb
<ul class="breadcrumb">
  <li><a href="#" id="a_style">Admin Panel</a> <span class="divider">/</span></li>
    <li><a href="#" id="a_style">Dashboard</a> <span class="divider">/</span></li>
    <li class="active">Paints</li>
</ul>
<h1 id="notice"><%= notice %></h1>

<div class="page-header">
  <h1>Paint <small>details infomation</small></h1>
</div>

<p class="lead" id="showtxt">
  <%= image_tag @paint.avatar.url(:medium) %>
</p>

<p class="lead" id="showtxt">
  <strong>Item code:</strong>
  <%= @paint.item_code %>
</p>

<p class="lead" id="showtxt">
  <strong>Title:</strong>
  <%= @paint.title %>
</p>

<p class="lead" id="showtxt">

  <strong>Paint Type:</strong>
  <%= @paint.paint_type.type_name rescue "-" %>
</p>


<p class="lead" id="showtxt">

  <strong>Size:</strong>
  <%= @paint.size.size rescue "-" %>
</p>

<p class="lead" id="showtxt">

  <strong>Price:</strong>
  <%= @paint.price rescue "-" %>
</p>
<p class="lead" id="showtxt">

  <strong>Artist Name:</strong>
  <%= @paint.artist.name rescue "-" %>
</p>


<p class="lead" id="showtxt">

  <strong>Is that new arrival:</strong>
  <%= @paint.new_arrival rescue "-" %>
</p>

<p class="lead" id="showtxt">

  <strong>Is that color cube art work:</strong>
  <%= @paint.our_artwork rescue "-" %>
</p>




<p class="lead" id="showtxt">

  <strong>Paint Type:</strong>
  <%= @paint.paint_type.type_name rescue "-" %>
</p>


<%= link_to 'Edit', edit_paint_path(@paint) %> |
<%= link_to 'Back', paints_path %>