config/routes.rb
Rails.application.routes.draw do
  resources :orders

  devise_for :admins, :controllers => {:sessions => "admins/sessions", :registrations => "admins/registrations"}

  resources :admins

  resources :paint_types

  resources :sizes

  resources :exhibitions

  resources :homes

  

  resources :photos

  resources :paints

  resources :artists

  root 'homes#home'
  get 'contact' => 'homes#contact'
  match 'contact',     to: 'homes#contact', via: 'get'
  get 'art_gallery' => 'homes#art_gallery'
  get 'artist_detail' => 'homes#artist'
  get 'photo_gallery' => 'homes#photo_gallery'
  get 'exhibition' => 'homes#exhibition'
  get 'terms_and_conditions' => 'homes#terms_and_conditions'
  get 'search' => 'homes#art_gallery'
  get 'search_photo' => 'homes#photo_gallery'
  get "artist_profile/:id" => "homes#artist_profile"
  get "artist_artwork" => "homes#artist_artwork"
  

 

 

 

end

app/controllers/paint_types_controller.rb
class PaintTypesController < ApplicationController
  before_action :set_paint_type, only: [:show, :edit, :update, :destroy]
  layout "backend"
  before_action :authenticate_admin!
  # GET /paint_types
  # GET /paint_types.json
  def index
    @paint_types = PaintType.all
  end

  # GET /paint_types/1
  # GET /paint_types/1.json
  def show
  end

  # GET /paint_types/new
  def new
    @paint_type = PaintType.new
  end

  # GET /paint_types/1/edit
  def edit
  end

  # POST /paint_types
  # POST /paint_types.json
  def create
    @paint_type = PaintType.new(paint_type_params)

    respond_to do |format|
      if @paint_type.save
        format.html { redirect_to @paint_type, notice: 'Paint type was successfully created.' }
        format.json { render :show, status: :created, location: @paint_type }
      else
        format.html { render :new }
        format.json { render json: @paint_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paint_types/1
  # PATCH/PUT /paint_types/1.json
  def update
    respond_to do |format|
      if @paint_type.update(paint_type_params)
        format.html { redirect_to @paint_type, notice: 'Paint type was successfully updated.' }
        format.json { render :show, status: :ok, location: @paint_type }
      else
        format.html { render :edit }
        format.json { render json: @paint_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paint_types/1
  # DELETE /paint_types/1.json
  def destroy
    @paint_type.destroy
    respond_to do |format|
      format.html { redirect_to paint_types_url, notice: 'Paint type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paint_type
      @paint_type = PaintType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paint_type_params
      params.require(:paint_type).permit(:type_name)
    end
end

app/helpers/paint_types_helper.rb
module PaintTypesHelper
end

app/views/paint_types/_form.html.erb
<%= form_for @paint_type, :html => { :class =>"form-horizontal" } do |f| %>
  <% if @paint_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paint_type.errors.count, "error") %> prohibited this paint_type from being saved:</h2>

      <ul>
      <% @paint_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="control-group">
    <label class="control-label" for="inputEmail">Types</label>
        <div class="controls">
    <%= f.text_field :type_name %>
  </div>
   </div>
   <div class="control-group">
        <div class="controls">
      <%= f.submit  :class => "btn" %>
  </div>
  </div>
<% end %>

app/views/paint_types/edit.html.erb
<ul class="breadcrumb">
	<li><a href="#" id="a_style">Admin Panel</a> <span class="divider">/</span></li>
    <li><a href="#" id="a_style">Dashboard</a> <span class="divider">/</span></li>
    <li class="active">Types</li>
</ul>
<div class="page-header">
  <h1>Edit Paint Types <small>details infomation</small></h1>
</div>

<%= render 'form' %>

<%= link_to 'Show', @paint_type %> |
<%= link_to 'Back', paint_types_path %>

app/views/paint_types/index.html.erb
<ul class="breadcrumb">
  <li><a href="#" id="a_style">Admin Panel</a> <span class="divider">/</span></li>
    <li><a href="#" id="a_style">Dashboard</a> <span class="divider">/</span></li>
    <li class="active">Types</li>
</ul>
<div class="page-header">
  <h1>Paint Types data<small> list of paint types infomation</small></h1>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Type name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paint_types.each do |paint_type| %>
      <tr>
        <td><%= paint_type.type_name rescue "-" %></td>
        <td><%= link_to 'Show', paint_type, :id => "a_style" %></td>
        <td><%= link_to 'Edit', edit_paint_type_path(paint_type), :id => "a_style" %></td>
        <td><%= link_to 'Destroy', paint_type, method: :delete, data: { confirm: 'Are you sure?' }, :id => "a_style" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paint type', new_paint_type_path, :class => "btn btn-default" %>

<br>

<br>

app/views/paint_types/new.html.erb
<ul class="breadcrumb">
	<li><a href="#" id="a_style">Admin Panel</a> <span class="divider">/</span></li>
    <li><a href="#" id="a_style">Dashboard</a> <span class="divider">/</span></li>
    <li class="active">Types</li>
</ul>
<div class="page-header">
  <h1>New Paint Types <small>data entry form</small></h1>
</div>


<%= render 'form' %>

<%= link_to 'Back', paint_types_path %>

app/views/paint_types/show.html.erb
<ul class="breadcrumb">
	<li><a href="#" id="a_style">Admin Panel</a> <span class="divider">/</span></li>
    <li><a href="#" id="a_style">Dashboard</a> <span class="divider">/</span></li>
    <li class="active">Types</li>
</ul>
<h1 id="notice"><%= notice %></h1>

<div class="page-header">
  <h1>Paint Types <small>details infomation</small></h1>
</div>

<p class="lead" id="showtxt">
  <strong>Type name:</strong>
  <%= @paint_type.type_name rescue "-" %>
</p>

<%= link_to 'Edit', edit_paint_type_path(@paint_type) %> |
<%= link_to 'Back', paint_types_path %>