config/routes.rb
Rails.application.routes.draw do
  resources :orders

  devise_for :admins, :controllers => {:sessions => "admins/sessions", :registrations => "admins/registrations"}

  resources :admins

  resources :paint_types

  resources :sizes

  resources :exhibitions

  resources :homes

  

  resources :photos

  resources :paints

  resources :artists

  root 'homes#home'
  get 'contact' => 'homes#contact'
  match 'contact',     to: 'homes#contact', via: 'get'
  get 'art_gallery' => 'homes#art_gallery'
  get 'artist_detail' => 'homes#artist'
  get 'photo_gallery' => 'homes#photo_gallery'
  get 'exhibition' => 'homes#exhibition'
  get 'terms_and_conditions' => 'homes#terms_and_conditions'
  get 'search' => 'homes#art_gallery'
  get 'search_photo' => 'homes#photo_gallery'
  get "artist_profile/:id" => "homes#artist_profile"
  get "artist_artwork" => "homes#artist_artwork"
  

 

 

 

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable


  devise :database_authenticatable,  :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:authentication_keys => [:user_name]
end

app/models/artist.rb
class Artist < ActiveRecord::Base

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


	has_many :paints

	has_many :photos
	
	PAINTER_TYPE = [
	"Painter",
	"Photographer"]

end

app/models/exhibition.rb
class Exhibition < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/models/home.rb
class Home < MailForm::Base

  attribute :name
  attribute :phone
  attribute :email
  attribute :message
  
  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "sent from our website",
      :to => "theldarlykhin.webdev@gmail.com",
      :from => %("#{name}")
    }

  end




end

app/models/order.rb
class Order < ActiveRecord::Base

end

app/models/paint.rb
class Paint < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  belongs_to :artist
  belongs_to :size
  belongs_to :paint_type

  before_save :generate_item_code


  	OUR_ARTWORK = ["YES","NO"]
  	NEW_ARRIVAL = ["YES","NO"]

	def self.search(paint_type_id,size_id,artist_id)
	  where('paint_type_id = ? AND size_id = ? AND artist_id = ?', "#{paint_type_id}", "#{size_id}", "#{artist_id}")
	end


	def generate_item_code
	

		number = Paint.maximum(:id).to_i + 1
	
		if
	   	 number.to_s.length == 1
			zero = "000"
	   		self.item_code = "CC-" + zero + number.to_s
	   	elsif
	   	 number.to_s.length == 2
			zero = "00"
	   		self.item_code = "CC-" + zero + number.to_s
	   	elsif
	   	 number.to_s.length == 3
			zero = "0"
	   		self.item_code = "CC-" + zero + number.to_s
	   	elsif
	   		number.to_s.length == 4
			number = Paint.last.id + 1
	   		self.item_code = "CC-" + number.to_s
	   	end
	end


  
end

app/models/paint_type.rb
class PaintType < ActiveRecord::Base
	has_many :paints
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  belongs_to :artist  
  belongs_to :size


  def self.search(color,size_id,artist_id)
  	where('color = ? OR size_id = ? OR artist_id = ?', "#{color}", "#{size_id}", "#{artist_id}")
  end


end

app/models/size.rb
class Size < ActiveRecord::Base
	has_many :paints
	has_many :photos

	
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/controllers_helper.rb
module ControllersHelper
end

app/helpers/exhibitions_helper.rb
module ExhibitionsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/paint_types_helper.rb
module PaintTypesHelper
end

app/helpers/paints_helper.rb
module PaintsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>


<head>
  <title>ColorCube ArtGallery</title>
  <meta name="myanmar art" 
      content="wazo myanmar art galleries is an collection of myanmar artisti's artworks">
  <meta name="myanamar painting" 
      content="wazo myanmar art galleries is an collection of myanmar artisti's artworks">

	 <%= stylesheet_link_tag    'bootstrap.css' %>
	 <%= stylesheet_link_tag    'responsive.css' %>
	 <%= stylesheet_link_tag    'style.css' %>
	 <%= stylesheet_link_tag    'touchTouch.css' %>
	 <%= stylesheet_link_tag    'kwicks-slider.css' %>

   <%= javascript_include_tag 'jquery.js' %>
   <%= javascript_include_tag 'holder.js' %>
   <%= javascript_include_tag 'superfish.js' %>
	 <%= javascript_include_tag 'jquery.flexslider-min.js' %>
	 <%= javascript_include_tag 'jquery.kwicks-1.5.1.js' %>
	 <%= javascript_include_tag 'jquery.easing.1.3.js' %>	  
	 <%= javascript_include_tag 'touchTouch.jquery.js' %>


	<script type="text/javascript">if($(window).width()>1024){document.write("<"+"script src='/assets/jquery.preloader.js'></"+"script>");}	</script>

	<script>		
		 jQuery(window).load(function() {	
		 $x = $(window).width();		
	if($x > 1024)
	{			
	jQuery("#content .row").preloader();    }	
		 
     jQuery('.magnifier').touchTouch();			
    jQuery('.spinner').animate({'opacity':0},1000,'easeOutCubic',function (){jQuery(this).css('display','none')});	
  		  }); 
				
	</script>
	

	</head>

	<body>
<div class="spinner"></div>



<%= yield %>

<!--============================== footer =================================-->
<footer>
      <div class="container clearfix">
    <ul class="list-social pull-right">
          <li><a class="icon-1" href="#"></a></li>
          <li><a class="icon-2" href="#"></a></li>
          <li><a class="icon-3" href="#"></a></li>
          <li><a class="icon-4" href="#"></a></li>
        </ul>
    <div class="privacy pull-left">Copyright 2015 H&T techs - Produce an App for Others is Worth Living. Produced by <a href="http://www.hnttechs.com" target="_blank" rel="nofollow">H&T techs</a> </div>
  </div>
    </footer>
 <%= javascript_include_tag "bootstrap.js" %>
</body>
</html>

app/views/layouts/backend.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WazoGallery</title>
  <%= stylesheet_link_tag    'bootstrap.css' %>
  <%= stylesheet_link_tag    'backend_style.css' %>
  <%= javascript_include_tag 'jquery.js' %>
  <%= javascript_include_tag 'jquery_ujs.js' %>
  <%= javascript_include_tag 'bootstrap-dropdown.js' %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if admin_signed_in? %>
<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">Dashboard</a>
    <ul class="nav">
      <li><a href="/orders">Orders</a></li>
      <li><a href="/exhibitions">Exhibitions</a></li>
      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Artists <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="/artists">List of artists</a></li>
                <li><a href="/artists/new">New artist</a></li>
              </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Arts<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="/paints">Paints</a></li>
                <li><a href="/photos">Photos</a></li>
              </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Others<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="/sizes">Sizes</a></li>
                <li><a href="/paint_types">Types</a></li>
              </ul>
        </li>



              
                        <li><%= link_to "Account Setting", edit_admin_registration_path %></li>
                        <li><%= link_to "Logout", destroy_admin_session_path, method: :delete  %></li>
        
       
            



    </ul>
  </div>
</div>
<% end %>

    <div class="container">

    		<%= yield %>
    </div>

</body>
</html>

app/views/order_notifier/send_order_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Thanks for signing up, <%= @order.customer_name %>!</h1>
    <p>Thanks for joining and have a great day! Now sign in and do
awesome things!</p>
  </body>
</html>